import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const check = process.argv.includes("--check");
const result = await build({
  entryPoints: [resolve(root, "widget/cycle-controller.ts")],
  bundle: true,
  format: "esm",
  platform: "browser",
  target: ["es2022"],
  minify: true,
  write: false,
  legalComments: "none"
});
const script = result.outputFiles[0]?.text;
if (!script) throw new Error("Widget build produced no JavaScript.");
const output = resolve(root, "src/generated-widget.ts");
const generated = `// GENERATED by scripts/build-widget.mjs; do not edit.\nexport const generatedCycleControllerScript = ${JSON.stringify(script)};\n`;
if (check) {
  const existing = await readFile(output, "utf8").catch(() => "");
  if (existing !== generated) {
    console.error("Generated widget is missing or stale. Run npm run build:widget.");
    process.exitCode = 1;
  } else {
    console.log(`Generated VPP cycle controller is current (${Buffer.byteLength(script)} bytes).`);
  }
} else {
  await writeFile(output, generated, "utf8");
  console.log(`Built VPP cycle controller (${Buffer.byteLength(script)} bytes).`);
}
